version: '3.3'

services:
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: kids
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
